config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    def index
    end
    
    def new
        @project = Project.new
    end

    def show
        @project = Project.find(params[:id])
    end

    def create
        @project = Project.new(project_params)
        if @project.save
            flash[:notice] = "Project has been created."
            redirect_to @project
        else
            # nothing, yet
        end
    end
end

private
    def project_params
        params.require(:project).permit(:name, :description)
    end

app/helpers/application_helper.rb
module ApplicationHelper
    def title(*parts)
        unless parts.empty?
            content_for :title do
            (parts << "Ticketee").join(" - ")
            end
        end
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
   <title>
        <% if content_for?(:title) %>
        <%= yield(:title) %>
        <% else %>
          Ticketee
        <% end %>
  </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% flash.each do |key, message| %>
        <div><%= message %></div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>
    <%= form_for(@project) do |f| %>
        <p>
            <%= f.label :name %><br>
            <%= f.text_field :name %>
        </p>
        
        <p>
            <%= f.label :description %><br>
            <%= f.text_field :description %>
        </p>
        <%= f.submit %>
<% end %>

app/views/projects/show.html.erb
<% title(@project.name, "Projects") %>
<p><%= @project.description %></p>